name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install
      run: sudo apt-get install emacs && emacs --version

    - name: Compile
      run: make

    - name: Run tests
      run: make test
